---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: secret-validator-ns
  name: secret-validator-example-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
